schema_version = "1"
generated_by = "mustflow"

[template]
id = "default"
version = "0.1.0"
profile = "oss"
locale = "en"

[files."AGENTS.md"]
source = "template_locale"
last_action = "updated"
content_hash = "sha256:5af7a89f4e8c1adffeaa1f84492cb988be68b5cb0e62bafc2668f208a5b0eef9"

[files.".mustflow/context/INDEX.md"]
source = "template_locale"
last_action = "created"
content_hash = "sha256:a9b3319ff6b3fa2bce964fccba586eb55b75fb576c869310ad03b1f14934fe9b"

[files.".mustflow/context/PROJECT.md"]
source = "template_locale"
last_action = "created"
content_hash = "sha256:d2ef6692a0551b18bc24996c976890e190b2f385b54404486cd0478f11da7904"

[files.".mustflow/skills/INDEX.md"]
source = "template_locale"
last_action = "created"
content_hash = "sha256:3a63e00c2048b9f81145b52d29e498b1bf14bf384d5424d1bda1feba3b29d507"

[files.".mustflow/skills/code-review/SKILL.md"]
source = "template_locale"
last_action = "created"
content_hash = "sha256:9deb575506d4d6e1ca2e7df411b40023ed27ad7daae0b74e4d93cbf35f8bd665"

[files.".mustflow/skills/test-maintenance/SKILL.md"]
source = "template_locale"
last_action = "created"
content_hash = "sha256:a458198012c2d9ba892e3b54f57a2403af665b92c8b3c7430c1861b3db685f70"

[files.".mustflow/skills/failure-triage/SKILL.md"]
source = "template_locale"
last_action = "created"
content_hash = "sha256:417b38e2da2917af946bcb409eb72de03922ade6238ec19460dfd85894137fb8"

[files.".mustflow/skills/docs-update/SKILL.md"]
source = "template_locale"
last_action = "created"
content_hash = "sha256:7789ab2e3374d9c8257bed3dbf2e8ad2af75f91713438706656345a6813de59b"

[files.".mustflow/docs/agent-workflow.md"]
source = "template_locale"
last_action = "updated"
content_hash = "sha256:f1a876f732fbdc2d560ce30bc06f33454f0674101ee3d13f4e01f6dc5efbcf4a"

[files.".mustflow/config/mustflow.toml"]
source = "template_common"
last_action = "updated"
content_hash = "sha256:4bc48d56de0afc3d2e885adeefcbe4b9cee3263c32db29e12c78dd1a20be946e"

[files.".mustflow/config/commands.toml"]
source = "template_common"
last_action = "created"
content_hash = "sha256:4117a3c7af6a96a66c2c7e15a1107cb032b8ac6076c59032cbb585105035d25f"

[files.".mustflow/config/preferences.toml"]
source = "template_common"
last_action = "customized"
content_hash = "sha256:2b5ce94bbaf786f2c0eafdc19c56e7db73b2edbf1cd93619991e9bb5e9c9a929"
