schema_version = "1"

[template]
id = "default"
version = "2.24.0"
profile = "library"
locale = "en"

[files."AGENTS.md"]
source = "template_locale"
last_action = "customized"
content_hash = "sha256:56ec13b21a71535cb9427aa0e69410d3cb99c8950f37f6480fe14bf8b2cd1b90"

[files.".mustflow/config/commands.toml"]
source = "repository"
last_action = "customized"
content_hash = "sha256:e5f7296dc9d1abb14b9f7f44e2d943a10fbd82380744efe2c7e2a57e70485ca5"

[files.".mustflow/docs/agent-workflow.md"]
source = "template_common"
last_action = "customized"
content_hash = "sha256:fc6905cf2da26f213684335ae8f6db287bd2e9099b60253a103938730a761314"

[files.".mustflow/config/mustflow.toml"]
source = "template_common"
last_action = "customized"
content_hash = "sha256:5ea054a8dc3dfb0e196667874d346a09cd3caeb05f73ecc3b6e2dc17958424c0"

[files.".mustflow/context/PROJECT.md"]
source = "template_common"
last_action = "customized"
content_hash = "sha256:7a375a484e441d2ba82adabe4e98ca09cc6cfaa19ccb32642cba7474c7e5d80b"

[files.".mustflow/skills/router.toml"]
source = "template_locale"
last_action = "customized"
content_hash = "sha256:f02d5a92a5fe3adbd109f10992703414b9451c97e1457fa3174916d9df04dab1"
