export interface PublicJsonSchemaContract {
	readonly id: string;
	readonly schemaFile: string;
	readonly producer: string;
	readonly packaged: true;
	readonly documented: true;
	readonly installedCommand?: readonly string[];
	readonly expectedExitCodes?: readonly number[];
}

const PUBLIC_JSON_SCHEMA_CONTRACTS: readonly PublicJsonSchemaContract[] = [
	{
		id: 'adapter-compatibility-report',
		schemaFile: 'adapter-compatibility-report.schema.json',
		producer: 'mf adapters status --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'adapters', 'status', '--json'],
	},
	{
		id: 'doctor-report',
		schemaFile: 'doctor-report.schema.json',
		producer: 'mf doctor --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'doctor', '--json'],
	},
	{
		id: 'context-report',
		schemaFile: 'context-report.schema.json',
		producer: 'mf context --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'context', '--json'],
	},
	{
		id: 'workspace-summary',
		schemaFile: 'workspace-summary.schema.json',
		producer: 'mf api workspace-summary --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'workspace-summary', '--json'],
	},
	{
		id: 'command-catalog',
		schemaFile: 'command-catalog.schema.json',
		producer: 'mf api command-catalog --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'command-catalog', '--json'],
	},
	{
		id: 'verification-plan',
		schemaFile: 'verification-plan.schema.json',
		producer: 'mf api verification-plan --changed --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'verification-plan', '--changed', '--json'],
	},
	{
		id: 'latest-evidence',
		schemaFile: 'latest-evidence.schema.json',
		producer: 'mf api latest-evidence --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'latest-evidence', '--json'],
	},
	{
		id: 'diff-risk',
		schemaFile: 'diff-risk.schema.json',
		producer: 'mf api diff-risk --changed --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'diff-risk', '--changed', '--json'],
	},
	{
		id: 'health',
		schemaFile: 'health.schema.json',
		producer: 'mf api health --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'health', '--json'],
	},
	{
		id: 'locks',
		schemaFile: 'locks.schema.json',
		producer: 'mf api locks --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'locks', '--json'],
	},
	{
		id: 'api-serve-response',
		schemaFile: 'api-serve-response.schema.json',
		producer: 'mf api serve --stdio',
		packaged: true,
		documented: true,
	},
	{
		id: 'run-receipt',
		schemaFile: 'run-receipt.schema.json',
		producer: 'mf run <intent> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'run', 'mustflow_check', '--json'],
	},
	{
		id: 'commands',
		schemaFile: 'commands.schema.json',
		producer: 'parsed .mustflow/config/commands.toml',
		packaged: true,
		documented: true,
	},
	{
		id: 'test-selection',
		schemaFile: 'test-selection.schema.json',
		producer: 'parsed .mustflow/config/test-selection.toml',
		packaged: true,
		documented: true,
	},
	{
		id: 'contract-lint-report',
		schemaFile: 'contract-lint-report.schema.json',
		producer: 'mf contract-lint --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'contract-lint', '--json'],
	},
	{
		id: 'onboard-commands-report',
		schemaFile: 'onboard-commands-report.schema.json',
		producer: 'mf onboard commands --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'onboard', 'commands', '--json'],
	},
	{
		id: 'next-report',
		schemaFile: 'next-report.schema.json',
		producer: 'mf next --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'next', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'evidence-report',
		schemaFile: 'evidence-report.schema.json',
		producer: 'mf evidence --changed --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'evidence', '--changed', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'workspace-status',
		schemaFile: 'workspace-status.schema.json',
		producer: 'mf workspace status --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'workspace', 'status', '--json'],
	},
	{
		id: 'workspace-command-catalog',
		schemaFile: 'workspace-command-catalog.schema.json',
		producer: 'mf workspace command-catalog --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'workspace', 'command-catalog', '--json'],
	},
	{
		id: 'workspace-verification-plan',
		schemaFile: 'workspace-verification-plan.schema.json',
		producer: 'mf workspace verify --changed --plan-only --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'workspace', 'verify', '--changed', '--plan-only', '--json'],
	},
	{
		id: 'dashboard-export',
		schemaFile: 'dashboard-export.schema.json',
		producer: 'mf dashboard --export-json <path>',
		packaged: true,
		documented: true,
	},
	{
		id: 'classify-report',
		schemaFile: 'classify-report.schema.json',
		producer: 'mf classify <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'classify', 'README.md', '--json'],
	},
	{
		id: 'impact-report',
		schemaFile: 'impact-report.schema.json',
		producer: 'mf impact <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'impact', 'package.json', '--json'],
	},
	{
		id: 'line-endings-report',
		schemaFile: 'line-endings-report.schema.json',
		producer: 'mf line-endings check --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'line-endings', 'check', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'latest-run-pointer',
		schemaFile: 'latest-run-pointer.schema.json',
		producer: '.mustflow/state/runs/latest.json when written by mf verify',
		packaged: true,
		documented: true,
	},
	{
		id: 'handoff-validation-report',
		schemaFile: 'handoff-validation-report.schema.json',
		producer: 'mf handoff validate <path> --json',
		packaged: true,
		documented: true,
		expectedExitCodes: [0, 1],
	},
	{
		id: 'version-sources-report',
		schemaFile: 'version-sources-report.schema.json',
		producer: 'mf version-sources --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'version-sources', '--json'],
	},
	{
		id: 'docs-review-list',
		schemaFile: 'docs-review-list.schema.json',
		producer: 'mf docs review list --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'docs', 'review', 'list', '--json'],
	},
	{
		id: 'explain-report',
		schemaFile: 'explain-report.schema.json',
		producer: 'mf explain <topic> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'explain', 'authority', 'AGENTS.md', '--json'],
	},
	{
		id: 'verify-report',
		schemaFile: 'verify-report.schema.json',
		producer: 'mf verify --reason <event> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'verify', '--reason', 'schema_verify', '--json'],
	},
	{
		id: 'verify-run-manifest',
		schemaFile: 'verify-run-manifest.schema.json',
		producer: '.mustflow/state/runs/verify-*/manifest.json',
		packaged: true,
		documented: true,
	},
	{
		id: 'change-verification-report',
		schemaFile: 'change-verification-report.schema.json',
		producer: 'mf verify --reason <event> --plan-only --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'verify', '--reason', 'schema_verify', '--plan-only', '--json'],
	},
];

export function getPublicJsonSchemaContracts(): readonly PublicJsonSchemaContract[] {
	return PUBLIC_JSON_SCHEMA_CONTRACTS;
}

export function getPublicJsonSchemaFiles(): readonly string[] {
	return PUBLIC_JSON_SCHEMA_CONTRACTS.map((contract) => contract.schemaFile);
}
