export interface PublicJsonSchemaContract {
	readonly id: string;
	readonly schemaFile: string;
	readonly producer: string;
	readonly packaged: true;
	readonly documented: true;
	readonly installedCommand?: readonly string[];
	readonly expectedExitCodes?: readonly number[];
}

const PUBLIC_JSON_SCHEMA_CONTRACTS: readonly PublicJsonSchemaContract[] = [
	{
		id: 'adapter-compatibility-report',
		schemaFile: 'adapter-compatibility-report.schema.json',
		producer: 'mf adapters status --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'adapters', 'status', '--json'],
	},
	{
		id: 'doctor-report',
		schemaFile: 'doctor-report.schema.json',
		producer: 'mf doctor --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'doctor', '--json'],
	},
	{
		id: 'check-report',
		schemaFile: 'check-report.schema.json',
		producer: 'mf check --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'check', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'status-report',
		schemaFile: 'status-report.schema.json',
		producer: 'mf status --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'status', '--json'],
	},
	{
		id: 'context-report',
		schemaFile: 'context-report.schema.json',
		producer: 'mf context --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'context', '--json'],
	},
	{
		id: 'workspace-summary',
		schemaFile: 'workspace-summary.schema.json',
		producer: 'mf api workspace-summary --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'workspace-summary', '--json'],
	},
	{
		id: 'command-catalog',
		schemaFile: 'command-catalog.schema.json',
		producer: 'mf api command-catalog --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'command-catalog', '--json'],
	},
	{
		id: 'verification-plan',
		schemaFile: 'verification-plan.schema.json',
		producer: 'mf api verification-plan --changed --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'verification-plan', '--changed', '--json'],
	},
	{
		id: 'latest-evidence',
		schemaFile: 'latest-evidence.schema.json',
		producer: 'mf api latest-evidence --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'latest-evidence', '--json'],
	},
	{
		id: 'diff-risk',
		schemaFile: 'diff-risk.schema.json',
		producer: 'mf api diff-risk --changed --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'diff-risk', '--changed', '--json'],
	},
	{
		id: 'health',
		schemaFile: 'health.schema.json',
		producer: 'mf api health --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'health', '--json'],
	},
	{
		id: 'locks',
		schemaFile: 'locks.schema.json',
		producer: 'mf api locks --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'api', 'locks', '--json'],
	},
	{
		id: 'api-serve-response',
		schemaFile: 'api-serve-response.schema.json',
		producer: 'mf api serve --stdio',
		packaged: true,
		documented: true,
	},
	{
		id: 'run-receipt',
		schemaFile: 'run-receipt.schema.json',
		producer: 'mf run <intent> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'run', 'mustflow_check', '--json'],
	},
	{
		id: 'commands',
		schemaFile: 'commands.schema.json',
		producer: 'parsed .mustflow/config/commands.toml',
		packaged: true,
		documented: true,
	},
	{
		id: 'test-selection',
		schemaFile: 'test-selection.schema.json',
		producer: 'parsed .mustflow/config/test-selection.toml',
		packaged: true,
		documented: true,
	},
	{
		id: 'contract-lint-report',
		schemaFile: 'contract-lint-report.schema.json',
		producer: 'mf contract-lint --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'contract-lint', '--json'],
	},
	{
		id: 'onboard-commands-report',
		schemaFile: 'onboard-commands-report.schema.json',
		producer: 'mf onboard commands --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'onboard', 'commands', '--json'],
	},
	{
		id: 'next-report',
		schemaFile: 'next-report.schema.json',
		producer: 'mf next --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'next', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'evidence-report',
		schemaFile: 'evidence-report.schema.json',
		producer: 'mf evidence --changed --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'evidence', '--changed', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'workspace-status',
		schemaFile: 'workspace-status.schema.json',
		producer: 'mf workspace status --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'workspace', 'status', '--json'],
	},
	{
		id: 'workspace-command-catalog',
		schemaFile: 'workspace-command-catalog.schema.json',
		producer: 'mf workspace command-catalog --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'workspace', 'command-catalog', '--json'],
	},
	{
		id: 'workspace-verification-plan',
		schemaFile: 'workspace-verification-plan.schema.json',
		producer: 'mf workspace verify --changed --plan-only --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'workspace', 'verify', '--changed', '--plan-only', '--json'],
	},
	{
		id: 'dashboard-export',
		schemaFile: 'dashboard-export.schema.json',
		producer: 'mf dashboard --export-json <path>',
		packaged: true,
		documented: true,
	},
	{
		id: 'classify-report',
		schemaFile: 'classify-report.schema.json',
		producer: 'mf classify <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'classify', 'README.md', '--json'],
	},
	{
		id: 'impact-report',
		schemaFile: 'impact-report.schema.json',
		producer: 'mf impact <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'impact', 'package.json', '--json'],
	},
	{
		id: 'line-endings-report',
		schemaFile: 'line-endings-report.schema.json',
		producer: 'mf line-endings check --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'line-endings', 'check', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'quality-gaming-report',
		schemaFile: 'quality-gaming-report.schema.json',
		producer: 'mf quality check --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'quality', 'check', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'script-pack-catalog',
		schemaFile: 'script-pack-catalog.schema.json',
		producer: 'mf script-pack list --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'list', '--json'],
	},
	{
		id: 'index-report',
		schemaFile: 'index-report.schema.json',
		producer: 'mf index --dry-run --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'index', '--dry-run', '--json'],
	},
	{
		id: 'search-report',
		schemaFile: 'search-report.schema.json',
		producer: 'mf search <query> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'search', 'mustflow', '--json'],
	},
	{
		id: 'script-pack-suggestion-report',
		schemaFile: 'script-pack-suggestion-report.schema.json',
		producer: 'mf script-pack suggest --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'suggest',
			'--path',
			'AGENTS.md',
			'--phase',
			'before_change',
			'--json',
		],
	},
	{
		id: 'code-outline-report',
		schemaFile: 'code-outline-report.schema.json',
		producer: 'mf script-pack run code/outline scan <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'code/outline',
			'scan',
			'node_modules/mustflow/dist/cli/index.js',
			'--json',
		],
	},
	{
		id: 'dependency-graph-report',
		schemaFile: 'dependency-graph-report.schema.json',
		producer: 'mf script-pack run code/dependency-graph scan <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'code/dependency-graph',
			'scan',
			'node_modules/mustflow/dist/cli/index.js',
			'--json',
		],
	},
	{
		id: 'import-cycle-report',
		schemaFile: 'import-cycle-report.schema.json',
		producer: 'mf script-pack run code/import-cycle check <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'code/import-cycle',
			'check',
			'node_modules/mustflow/dist/cli/index.js',
			'--json',
		],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'module-boundary-report',
		schemaFile: 'module-boundary-report.schema.json',
		producer: 'mf script-pack run code/module-boundary check <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'code/module-boundary',
			'check',
			'node_modules/mustflow/dist/cli/index.js',
			'--json',
		],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'change-impact-report',
		schemaFile: 'change-impact-report.schema.json',
		producer: 'mf script-pack run code/change-impact analyze [path...] --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'code/change-impact',
			'analyze',
			'--base',
			'HEAD',
			'--json',
		],
	},
	{
		id: 'code-symbol-read-report',
		schemaFile: 'code-symbol-read-report.schema.json',
		producer: 'mf script-pack run code/symbol-read read <path> --start-line <line> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'code/symbol-read',
			'read',
			'node_modules/mustflow/dist/cli/index.js',
			'--start-line',
			'1',
			'--end-line',
			'10',
			'--json',
		],
	},
	{
		id: 'route-outline-report',
		schemaFile: 'route-outline-report.schema.json',
		producer: 'mf script-pack run code/route-outline scan <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'code/route-outline',
			'scan',
			'node_modules/mustflow/dist/cli/index.js',
			'--json',
		],
	},
	{
		id: 'export-diff-report',
		schemaFile: 'export-diff-report.schema.json',
		producer: 'mf script-pack run code/export-diff compare --json',
		packaged: true,
		documented: true,
	},
	{
		id: 'reference-drift-report',
		schemaFile: 'reference-drift-report.schema.json',
		producer: 'mf script-pack run docs/reference-drift check [path...] --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'docs/reference-drift',
			'check',
			'node_modules/mustflow/README.md',
			'node_modules/mustflow/schemas/README.md',
			'--json',
		],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'link-integrity-report',
		schemaFile: 'link-integrity-report.schema.json',
		producer: 'mf script-pack run docs/link-integrity check [path...] --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'docs/link-integrity',
			'check',
			'node_modules/mustflow/README.md',
			'node_modules/mustflow/schemas/README.md',
			'--json',
		],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'test-performance-report',
		schemaFile: 'test-performance-report.schema.json',
		producer: 'mf script-pack run test/performance-report summarize --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'test/performance-report', 'summarize', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'test-regression-selector-report',
		schemaFile: 'test-regression-selector-report.schema.json',
		producer: 'mf script-pack run test/regression-selector select --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'test/regression-selector', 'select', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'text-budget-report',
		schemaFile: 'text-budget-report.schema.json',
		producer: 'mf script-pack run core/text-budget check <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'core/text-budget',
			'check',
			'AGENTS.md',
			'--max',
			'1000000',
			'--json',
		],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'generated-boundary-report',
		schemaFile: 'generated-boundary-report.schema.json',
		producer: 'mf script-pack run repo/generated-boundary check <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'repo/generated-boundary',
			'check',
			'AGENTS.md',
			'.mustflow/config/manifest.lock.toml',
			'--json',
		],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'repo-merge-conflict-scan-report',
		schemaFile: 'repo-merge-conflict-scan-report.schema.json',
		producer: 'mf script-pack run repo/merge-conflict-scan check [path...] --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/merge-conflict-scan', 'check', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'repo-git-ignore-audit-report',
		schemaFile: 'repo-git-ignore-audit-report.schema.json',
		producer: 'mf script-pack run repo/git-ignore-audit audit [path...] --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/git-ignore-audit', 'audit', 'AGENTS.md', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'repo-manifest-lock-drift-report',
		schemaFile: 'repo-manifest-lock-drift-report.schema.json',
		producer: 'mf script-pack run repo/manifest-lock-drift check [path...] --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/manifest-lock-drift', 'check', 'AGENTS.md', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'skill-route-audit-report',
		schemaFile: 'skill-route-audit-report.schema.json',
		producer: 'mf script-pack run repo/skill-route-audit audit --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/skill-route-audit', 'audit', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'repo-version-source-report',
		schemaFile: 'repo-version-source-report.schema.json',
		producer: 'mf script-pack run repo/version-source inspect --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/version-source', 'inspect', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'repo-toolchain-provenance-report',
		schemaFile: 'repo-toolchain-provenance-report.schema.json',
		producer: 'mf script-pack run repo/toolchain-provenance inspect --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/toolchain-provenance', 'inspect', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'repo-automation-surface-report',
		schemaFile: 'repo-automation-surface-report.schema.json',
		producer: 'mf script-pack run repo/automation-surface inspect --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/automation-surface', 'inspect', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'repo-dependency-surface-report',
		schemaFile: 'repo-dependency-surface-report.schema.json',
		producer: 'mf script-pack run repo/dependency-surface inspect --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/dependency-surface', 'inspect', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'repo-approval-gate-report',
		schemaFile: 'repo-approval-gate-report.schema.json',
		producer: 'mf script-pack run repo/approval-gate check --action <type> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'repo/approval-gate',
			'check',
			'--action',
			'git_commit',
			'--json',
		],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'repo-deploy-surface-report',
		schemaFile: 'repo-deploy-surface-report.schema.json',
		producer: 'mf script-pack run repo/deploy-surface inspect --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/deploy-surface', 'inspect', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'config-chain-report',
		schemaFile: 'config-chain-report.schema.json',
		producer: 'mf script-pack run repo/config-chain inspect <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'repo/config-chain',
			'inspect',
			'node_modules/mustflow/dist/cli/index.js',
			'--json',
		],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'env-contract-report',
		schemaFile: 'env-contract-report.schema.json',
		producer: 'mf script-pack run repo/env-contract scan [path...] --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/env-contract', 'scan', 'AGENTS.md', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'secret-risk-scan-report',
		schemaFile: 'secret-risk-scan-report.schema.json',
		producer: 'mf script-pack run repo/secret-risk-scan scan [path...] --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/secret-risk-scan', 'scan', 'AGENTS.md', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'security-pattern-scan-report',
		schemaFile: 'security-pattern-scan-report.schema.json',
		producer: 'mf script-pack run repo/security-pattern-scan scan [path...] --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'script-pack', 'run', 'repo/security-pattern-scan', 'scan', 'AGENTS.md', '--json'],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'related-files-report',
		schemaFile: 'related-files-report.schema.json',
		producer: 'mf script-pack run repo/related-files map <path...> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'script-pack',
			'run',
			'repo/related-files',
			'map',
			'node_modules/mustflow/dist/cli/index.js',
			'--json',
		],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'skill-route-report',
		schemaFile: 'skill-route-report.schema.json',
		producer: 'mf skill route --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'skill',
			'route',
			'--task',
			'Change TypeScript CLI output',
			'--path',
			'src/cli/index.ts',
			'--reason',
			'code_change',
			'--json',
		],
	},
	{
		id: 'skill-import-report',
		schemaFile: 'skill-import-report.schema.json',
		producer: 'mf skill import <github-url> --json',
		packaged: true,
		documented: true,
		installedCommand: [
			'mf',
			'skill',
			'import',
			'https://github.com/example/agent-skills/blob/main/security-review/SKILL.md',
			'--dry-run',
			'--json',
		],
		expectedExitCodes: [0, 1],
	},
	{
		id: 'route-fixture',
		schemaFile: 'route-fixture.schema.json',
		producer: 'parsed .mustflow/skills/route-fixtures.json',
		packaged: true,
		documented: true,
	},
	{
		id: 'latest-run-pointer',
		schemaFile: 'latest-run-pointer.schema.json',
		producer: '.mustflow/state/runs/latest.json when written by mf verify',
		packaged: true,
		documented: true,
	},
	{
		id: 'handoff-validation-report',
		schemaFile: 'handoff-validation-report.schema.json',
		producer: 'mf handoff validate <path> --json',
		packaged: true,
		documented: true,
		expectedExitCodes: [0, 1],
	},
	{
		id: 'version-sources-report',
		schemaFile: 'version-sources-report.schema.json',
		producer: 'mf version-sources --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'version-sources', '--json'],
	},
	{
		id: 'docs-review-list',
		schemaFile: 'docs-review-list.schema.json',
		producer: 'mf docs review list --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'docs', 'review', 'list', '--json'],
	},
	{
		id: 'explain-report',
		schemaFile: 'explain-report.schema.json',
		producer: 'mf explain <topic> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'explain', 'authority', 'AGENTS.md', '--json'],
	},
	{
		id: 'verify-report',
		schemaFile: 'verify-report.schema.json',
		producer: 'mf verify --reason <event> --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'verify', '--reason', 'schema_verify', '--json'],
	},
	{
		id: 'verify-run-manifest',
		schemaFile: 'verify-run-manifest.schema.json',
		producer: '.mustflow/state/runs/verify-*/manifest.json',
		packaged: true,
		documented: true,
	},
	{
		id: 'change-verification-report',
		schemaFile: 'change-verification-report.schema.json',
		producer: 'mf verify --reason <event> --plan-only --json',
		packaged: true,
		documented: true,
		installedCommand: ['mf', 'verify', '--reason', 'schema_verify', '--plan-only', '--json'],
	},
];

export function getPublicJsonSchemaContracts(): readonly PublicJsonSchemaContract[] {
	return PUBLIC_JSON_SCHEMA_CONTRACTS;
}

export function getPublicJsonSchemaFiles(): readonly string[] {
	return PUBLIC_JSON_SCHEMA_CONTRACTS.map((contract) => contract.schemaFile);
}
