const englishSeedLocales = ['en', 'fr', 'hi'];

/**
 * @typedef {Record<string, string>} Translations
 * @typedef {{ en?: string, es?: string, zh?: string, hi?: string }} LocaleLabels
 */

/**
 * @param {LocaleLabels} [labels]
 * @returns {{ translations: Translations } | {}}
 */
const translated = ({ en, es, zh, hi } = {}) => {
	/** @type {Translations} */
	const translations = {};

	if (en) {
		for (const locale of englishSeedLocales) {
			translations[locale] = en;
		}
	}

	const esLabel = es || en;
	if (esLabel) {
		translations.es = esLabel;
	}

	const zhLabel = zh || en;
	if (zhLabel) {
		const label = zhLabel;
		translations.zh = label;
		translations['zh-CN'] = label;
	}

	const hiLabel = hi || en;
	if (hiLabel) {
		translations.hi = hiLabel;
	}

	return Object.keys(translations).length > 0 ? { translations } : {};
};

/**
 * @param {LocaleLabels & { label: string, link: string }} input
 */
const page = ({ label, en, es, zh, hi, link }) => ({
	label,
	...translated({ en, es, zh, hi }),
	link,
});

/**
 * @param {LocaleLabels & { label: string, items: any[] }} input
 */
const group = ({ label, en, es, zh, hi, items }) => ({
	label,
	...translated({ en, es, zh, hi }),
	items,
});

/**
 * @param {LocaleLabels & { label: string, directory: string }} input
 */
const autogeneratedGroup = ({ label, en, es, zh, hi, directory }) => ({
	label,
	...translated({ en, es, zh, hi }),
	autogenerate: { directory },
});

export const pages = {
	overview: page({ label: '개요', en: 'Overview', es: 'Resumen', zh: '概览', link: '/' }),
	rootAgents: page({ label: 'AGENTS.md', link: '/files/agents/' }),
	repoMap: page({ label: 'REPO_MAP.md', link: '/files/repo-map/' }),
	rootDocs: page({
		label: '루트 문서와 계약',
		en: 'Root docs and contracts',
		es: 'Documentos y contratos raíz',
		zh: '根文档和合同',
		hi: 'Root docs and contracts',
		link: '/files/root-docs/',
	}),
	commandsToml: page({ label: 'commands.toml', link: '/files/commands-toml/' }),
	mustflowToml: page({ label: 'mustflow.toml', link: '/files/mustflow-toml/' }),
	preferencesToml: page({ label: 'preferences.toml', link: '/files/preferences-toml/' }),
	manifestLockToml: page({ label: 'manifest.lock.toml', link: '/files/manifest-lock-toml/' }),
	jsonSchemas: page({ label: 'schemas/', link: '/files/json-schemas/' }),
	contextIndex: page({ label: 'INDEX.md', link: '/files/context-index/' }),
	projectContext: page({ label: 'PROJECT.md', link: '/files/project-context/' }),
	agentWorkflow: page({ label: 'agent-workflow.md', link: '/files/agent-workflow/' }),
	skillsIndex: page({ label: 'INDEX.md', link: '/files/skills-index/' }),
	skill: page({ label: '*/SKILL.md', link: '/files/skill/' }),
	templateManifest: page({ label: 'manifest.toml', link: '/files/manifest-toml/' }),
	i18n: page({ label: 'i18n.toml', link: '/files/i18n-toml/' }),
	operatingFlow: page({ label: '기본 운영 흐름', en: 'Operating flow', es: 'Flujo operativo', zh: '运行流程', hi: 'संचालन प्रवाह', link: '/design/operating-flow/' }),
	cliContract: page({ label: 'CLI 출력 계약', en: 'CLI output contract', es: 'Contrato de salida CLI', zh: 'CLI 输出合同', hi: 'CLI आउटपुट अनुबंध', link: '/design/cli-contract/' }),
	skillResources: page({ label: '스킬 보조 자원', en: 'Skill resources', es: 'Recursos de skills', zh: 'Skill 资源', hi: 'Skill संसाधन', link: '/design/skill-resources/' }),
	localIndex: page({ label: '로컬 색인', en: 'Local index', es: 'Índice local', zh: '本地索引', hi: 'स्थानीय सूचकांक', link: '/design/local-index/' }),
	harnessContracts: page({
		label: '하네스 계약',
		en: 'Harness contracts',
		es: 'Contratos de ejecución de agentes',
		zh: 'Harness 合同',
		hi: 'हार्नेस अनुबंध',
		link: '/design/harness-contracts/',
	}),
	instructionRefresh: page({
		label: '지침 새로고침',
		en: 'Instruction refresh',
		es: 'Actualización de instrucciones',
		zh: '指令刷新',
		hi: 'निर्देश ताज़ा करना',
		link: '/design/instruction-refresh/',
	}),
	workItems: page({ label: '작업 항목', en: 'Work items', es: 'Elementos de trabajo', zh: '工作项', hi: 'कार्य आइटम', link: '/design/work-items/' }),
	futureFeatures: page({ label: '검토 중인 기능', en: 'Future features', es: 'Funciones futuras', zh: '未来功能', hi: 'भविष्य की सुविधाएं', link: '/design/future-features/' }),
	updatePolicy: page({ label: 'mf update 정책', en: 'mf update policy', es: 'Política de mf update', zh: 'mf update 政策', hi: 'mf update नीति', link: '/design/update-policy/' }),
	manifestLockDecision: page({
		label: 'manifest.lock 구조 결정',
		en: 'manifest.lock decision',
		es: 'Decisión sobre manifest.lock',
		zh: 'manifest.lock 结构决策',
		hi: 'manifest.lock निर्णय',
		link: '/design/manifest-lock-decision/',
	}),
	releaseChecks: page({ label: '배포 전 확인', en: 'Release checks', es: 'Comprobaciones de publicación', zh: '发布前检查', hi: 'रिलीज़ जांचें', link: '/design/release-checks/' }),
	contractSpecs: page({
		label: '계약 명세',
		en: 'Contract specifications',
		es: 'Especificaciones de contrato',
		zh: '合同规范',
		hi: 'अनुबंध विनिर्देश',
		link: '/design/contract-specs/',
	}),
};

export const autogeneratedDirectories = ['commands'];

export const sidebarSections = [
	group({
		label: '시작',
		en: 'Start',
		es: 'Inicio',
		zh: '开始',
		items: [pages.overview],
	}),
	group({
		label: '파일',
		en: 'Files',
		es: 'Archivos',
		zh: '文件',
		hi: 'फ़ाइलें',
		items: [
			group({
				label: '루트 파일',
				en: 'Root files',
				es: 'Archivos raíz',
				zh: '根文件',
				hi: 'रूट फ़ाइलें',
				items: [pages.rootAgents, pages.repoMap, pages.rootDocs],
			}),
			group({
				label: '패키지 파일',
				en: 'Package files',
				es: 'Archivos del paquete',
				zh: '包文件',
				hi: 'पैकेज फ़ाइलें',
				items: [pages.jsonSchemas],
			}),
			group({
				label: '.mustflow/',
				items: [
					group({
						label: 'config/',
						items: [pages.commandsToml, pages.mustflowToml, pages.preferencesToml, pages.manifestLockToml],
					}),
					group({
						label: 'docs/',
						items: [pages.agentWorkflow],
					}),
					group({
						label: 'context/',
						items: [pages.contextIndex, pages.projectContext],
					}),
					group({
						label: 'skills/',
						items: [pages.skillsIndex, pages.skill],
					}),
				],
			}),
		],
	}),
	group({
		label: '템플릿 관리',
		en: 'Template management',
		es: 'Gestión de plantillas',
		zh: '模板管理',
		hi: 'टेम्पलेट प्रबंधन',
		items: [pages.templateManifest, pages.i18n],
	}),
	group({
		label: '설계',
		en: 'Design',
		es: 'Diseño',
		zh: '设计',
		hi: 'डिज़ाइन',
		items: [
			pages.operatingFlow,
			pages.cliContract,
			pages.skillResources,
			pages.localIndex,
			pages.harnessContracts,
			pages.instructionRefresh,
			pages.workItems,
			pages.futureFeatures,
			pages.updatePolicy,
			pages.manifestLockDecision,
			pages.releaseChecks,
			pages.contractSpecs,
		],
	}),
	autogeneratedGroup({
		label: '명령어',
		en: 'Commands',
		es: 'Comandos',
		zh: '命令',
		directory: autogeneratedDirectories[0],
	}),
];
