const translated = (en) => (en ? { translations: { en } } : {});

const page = ({ label, en, link }) => ({
	label,
	...translated(en),
	link,
});

const group = ({ label, en, items }) => ({
	label,
	...translated(en),
	items,
});

const autogeneratedGroup = ({ label, en, directory }) => ({
	label,
	...translated(en),
	autogenerate: { directory },
});

export const pages = {
	overview: page({ label: '개요', en: 'Overview', link: '/' }),
	rootAgents: page({ label: 'AGENTS.md', link: '/files/agents/' }),
	repoMap: page({ label: 'REPO_MAP.md', link: '/files/repo-map/' }),
	commandsToml: page({ label: 'commands.toml', link: '/files/commands-toml/' }),
	mustflowToml: page({ label: 'mustflow.toml', link: '/files/mustflow-toml/' }),
	preferencesToml: page({ label: 'preferences.toml', link: '/files/preferences-toml/' }),
	manifestLockToml: page({ label: 'manifest.lock.toml', link: '/files/manifest-lock-toml/' }),
	contextIndex: page({ label: 'INDEX.md', link: '/files/context-index/' }),
	projectContext: page({ label: 'PROJECT.md', link: '/files/project-context/' }),
	agentWorkflow: page({ label: 'agent-workflow.md', link: '/files/agent-workflow/' }),
	skillsIndex: page({ label: 'INDEX.md', link: '/files/skills-index/' }),
	skill: page({ label: '*/SKILL.md', link: '/files/skill/' }),
	templateManifest: page({ label: 'manifest.toml', link: '/files/manifest-toml/' }),
	i18n: page({ label: 'i18n.toml', link: '/files/i18n-toml/' }),
	operatingFlow: page({ label: '기본 운영 흐름', en: 'Operating flow', link: '/design/operating-flow/' }),
	cliContract: page({ label: 'CLI 출력 계약', en: 'CLI output contract', link: '/design/cli-contract/' }),
	skillResources: page({ label: '스킬 보조 자원', en: 'Skill resources', link: '/design/skill-resources/' }),
	localIndex: page({ label: '로컬 색인', en: 'Local index', link: '/design/local-index/' }),
	harnessContracts: page({
		label: '하네스 계약',
		en: 'Harness contracts',
		link: '/design/harness-contracts/',
	}),
	instructionRefresh: page({
		label: '지침 새로고침',
		en: 'Instruction refresh',
		link: '/design/instruction-refresh/',
	}),
	workItems: page({ label: '작업 항목', en: 'Work items', link: '/design/work-items/' }),
	futureFeatures: page({ label: '검토 중인 기능', en: 'Future features', link: '/design/future-features/' }),
	updatePolicy: page({ label: 'mf update 정책', en: 'mf update policy', link: '/design/update-policy/' }),
	manifestLockDecision: page({
		label: 'manifest.lock 구조 결정',
		en: 'manifest.lock decision',
		link: '/design/manifest-lock-decision/',
	}),
	releaseChecks: page({ label: '배포 전 확인', en: 'Release checks', link: '/design/release-checks/' }),
};

export const autogeneratedDirectories = ['commands'];

export const sidebarSections = [
	group({
		label: '시작',
		en: 'Start',
		items: [pages.overview],
	}),
	group({
		label: '파일',
		en: 'Files',
		items: [
			group({
				label: '루트 파일',
				en: 'Root files',
				items: [pages.rootAgents, pages.repoMap],
			}),
			group({
				label: '.mustflow/',
				items: [
					group({
						label: 'config/',
						items: [pages.commandsToml, pages.mustflowToml, pages.preferencesToml, pages.manifestLockToml],
					}),
					group({
						label: 'docs/',
						items: [pages.agentWorkflow],
					}),
					group({
						label: 'context/',
						items: [pages.contextIndex, pages.projectContext],
					}),
					group({
						label: 'skills/',
						items: [pages.skillsIndex, pages.skill],
					}),
				],
			}),
		],
	}),
	group({
		label: '템플릿 관리',
		en: 'Template management',
		items: [pages.templateManifest, pages.i18n],
	}),
	group({
		label: '설계',
		en: 'Design',
		items: [
			pages.operatingFlow,
			pages.cliContract,
			pages.skillResources,
			pages.localIndex,
			pages.harnessContracts,
			pages.instructionRefresh,
			pages.workItems,
			pages.futureFeatures,
			pages.updatePolicy,
			pages.manifestLockDecision,
			pages.releaseChecks,
		],
	}),
	autogeneratedGroup({
		label: '명령어',
		en: 'Commands',
		directory: autogeneratedDirectories[0],
	}),
];
